export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const RUCHER_REPOSITORY = Symbol('RUCHER_REPOSITORY');
export const RUCHE_REPOSITORY = Symbol('RUCHE_REPOSITORY');
export const INSPECTION_REPOSITORY = Symbol('INSPECTION_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
